Repository TencentBlueKing/bk-ci, pull requests merged in 2020-10, with the labels that each got.

#2446 feature: 添加traceId  去skywalking #1824
  src/backend/ci/core/common/common-event/build.gradle
  src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/listener/pipeline/BaseListener.kt
  src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/pojo/pipeline/IPipelineEvent.kt
  src/backend/ci/core/common/common-service/build.gradle
  src/backend/ci/core/common/common-service/src/main/java/com/tencent/devops/common/service/Log4j2Initializer.java
  src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/trace/TraceFilter.kt
  src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/trace/TraceTag.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
Labels: area/ci/backend

#2703 feat: JOB配额增加工蜂CI类型 #2702
  src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/pojo/enums/JobQuotaVmType.kt
Labels: area/ci/backend, test/passed

#2687 feat: 提供第三方构建机列表及状态的OpenAPI接口 #2675
  src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwEnvironmentResourceV3.kt
  src/backend/ci/core/openapi/biz-openapi/build.gradle
  src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwEnvironmentResourceV3Impl.kt
Labels: area/ci/backend, test/passed

#2723 bugfix: 获取日志为空问题 #2318
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/enums/BuildStatus.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
Labels: test/passed

#2756 feat: 拆离turbo强依赖 #2726
  src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildExtServiceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildExtService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
Labels: test/passed

#2806 chore: 微服务access_log日志中耗时配置 #2805
  src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/WebAutoConfiguration.kt
  src/backend/ci/core/common/common-web/src/main/resources/common-web.properties
Labels: test/passed

#2783 bug：新增凭据型切换类型不触发数据变更
  src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
  src/frontend/devops-pipeline/src/components/Stages/AtomList.vue
  src/frontend/devops-ticket/src/views/create_credential.vue
Labels: test/passed

#2834 fix: 构建机启动时间超过120秒时会导致Agent心跳超时判定消息事件提前结束 #2365
  src/backend/ci/core/process/biz-process-sample/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildExtServiceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildBuildResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchBuildLessDockerStartupTaskAtom.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/HeartbeatControl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/run/monitor/PipelineBuildHeartbeatListener.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildExtService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineVMBuildService.kt
Labels: test/passed

#2785 perf: 执行预览页面的编排滚动条优化
  src/frontend/devops-pipeline/src/components/Pipeline.vue
  src/frontend/devops-pipeline/src/components/template/instance-compared.vue
  src/frontend/devops-pipeline/src/views/subpages/preview.vue
Labels: test/passed
