Repository TencentBlueKing/bk-ci, pull requests merged in 2020-08, with the labels that each got.

#2338 refactor: 并发下docker容器状态同步异常 #2109
  src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/DockerHostBuildService.kt
Labels: area/ci/backend, stage/test, test/passed

#2334 refactor: pcg构建机，构建成功删除workspace时去掉软链 #2265
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
Labels: area/ci/agent, stage/test, test/passed

#2337 chore: 为agent-less模块增加启动脚本 #2335
  scripts/generate_boot.sh
Labels: kind/chore

#2308 bugfix: agent检测版本冲突报 permission denied #2128
  src/agent/src/pkg/config/version.go
Labels: test/passed

#2389 chore: issue管理优化 #2388
  .github/issue_template.md
  .github/workflows/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/ISSUE_TEMPLATE/enhancement.md
  .github/workflows/ISSUE_TEMPLATE/support.md
  .github/workflows/stale.yml
Labels: kind/chore

#2320 issue: image模块新增镜像详情接口 #2313
  src/backend/ci/core/image/api-image/src/main/kotlin/com/tencent/devops/image/api/ServiceDockerImageResource.kt
  src/backend/ci/core/image/api-image/src/main/kotlin/com/tencent/devops/image/pojo/CheckDockerImageRequest.kt
  src/backend/ci/core/image/api-image/src/main/kotlin/com/tencent/devops/image/pojo/CheckDockerImageResponse.kt
  src/backend/ci/core/image/biz-image/src/main/kotlin/com/tencent/devops/image/resources/ServiceDockerImageResourceImpl.kt
  src/backend/ci/core/image/biz-image/src/main/kotlin/com/tencent/devops/image/service/InspectImageService.kt
  src/backend/ci/core/image/biz-image/src/main/kotlin/com/tencent/devops/image/utils/CommonUtils.kt
Labels: area/ci/backend, stage/test, test/passed

#2384 feature: 版本仓库灰度配置优化 #2379
  src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/gray/RepoGray.kt
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/op/OPProjectResource.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OPProjectResourceImpl.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/OpProjectService.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
Labels: test/passed

#2378 bugfix: 短时间内连续点击“执行”按钮会出现多个构建任务，容易误操作 issue #890
  src/frontend/devops-nav/src/components/User/index.vue
  src/frontend/devops-pipeline/src/components/pipeline/triggers.vue
  src/frontend/devops-pipeline/src/mixins/pipeline-operate-mixin.js
Labels: stage/test, test/passed
