Repository TencentBlueKing/bk-ci, pull requests merged in 2021-11, with the labels that each got.

#5495 bugfix: 修复词法分析遇到 / 等符号解析错误的问题 #5477
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/expression/Lex.kt
  src/backend/ci/core/common/common-api/src/test/kotlin/com/tencent/devops/common/api/expression/GrammarAnalysisTest.kt
Labels: kind/bug, streams/test/passed, streams/stage/test

#5588 feat：biz-process下pipelineUrlBean+DefaultPipelineUrlBeanImpl转移到公共部分biz-base
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/bean/DefaultPipelineUrlBeanImpl.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/bean/PipelineUrlBean.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/config/PipelineUrlBeanConfiguration.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildBuildResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/notify/PipelineBuildNotifyListener.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/notify/PipelineExtendsNotifyConfiguration.kt
Labels: test/passed

#5596 feat：bazel cache rsyn时排除install和cache目录 #5595
  src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/AbstractDockerHostBuildService.kt
Labels: test/passed

#5602 Issue 5595 exclude bazel cache dir
  src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/AbstractDockerHostBuildService.kt
Labels: test/passed

#5656 [开源初始化脚本]perf: Windows构建机的batch脚本执行编码问题 #4601
  support-files/sql/5001_ci_store-init_dml_mysql.sql
Labels: kind/chore, kind/version/sample
