Repository TencentBlueKing/bk-ci, pull requests merged in 2021-12, with the labels that each got.

#5317 fix: 容器化相关bug修复 #5316
  src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/AuthConfiguration.kt
  src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkPermissionProjectService.kt
  src/backend/ci/core/auth/biz-auth-blueking/src/main/kotlin/com/tencent/devops/auth/service/BkPermissionService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/common/AuthCoreConfiguration.kt
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/service/IamEsbService.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
Labels: review needed

#5813 feat: 插件SDK中下载api优先使用制品库网关 #5812
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
Labels: stage/test, test/passed

#5811 bug: 研发商店查看质量红线指标界面，过滤掉已下架的指标 #5810
  src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityIndicatorService.kt
Labels: area/ci/backend
