Repository TencentBlueKing/bk-ci, pull requests merged in 2021-04, with the labels that each got.

#3858 研发商店新增插件数据相关图表
  src/frontend/devops-atomstore/package.json
  src/frontend/devops-atomstore/src/api/index.js
  src/frontend/devops-atomstore/src/assets/scss/devops-common.scss
  src/frontend/devops-atomstore/src/components/common/detail-info/atom.vue
  src/frontend/devops-atomstore/src/components/manage/over-view/total-static/index.vue
  src/frontend/devops-atomstore/src/components/manage/over-view/trend/atom.vue
  src/frontend/devops-atomstore/src/components/manage/over-view/trend/common.vue
  src/frontend/devops-atomstore/src/components/manage/over-view/trend/index.vue
  src/frontend/devops-atomstore/src/store/atom.js
  src/frontend/devops-atomstore/src/views/market/detail.vue
  src/frontend/devops-nav/package.json
  src/frontend/devops-nav/src/index.ts
  src/frontend/locale/store/en-US.json
  src/frontend/locale/store/zh-CN.json
  src/frontend/webpack.base.js
Labels: test/passed

#3912 feat: yaml是否展示的开关放开 #3910
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/service/atom/impl/MarketAtomServiceImpl.kt
Labels: stage/test, test/passed

#3965 pref: 签名模块优化与增加业务指标采集 #3960
  src/backend/ci/check.yml
  src/backend/ci/core/sign/biz-sign-sample/src/main/kotlin/com/tencent/devops/sign/service/impl/ArchiveServiceImpl.kt
  src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/impl/SignServiceImpl.kt
  src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/jmx/SignBean.kt
  src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/AsyncSignService.kt
  src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/service/SignService.kt
  src/backend/ci/core/sign/biz-sign/src/main/kotlin/com/tencent/devops/sign/utils/SignUtils.kt
Labels: review needed
