Repository TencentBlueKing/bk-ci, pull requests merged in 2021-01, with the labels that each got.

#3425 feat: openapi提供根据指定构建ID+变量名查出具体变量值接口 issue #3368
  src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
  src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/ApigwBuildResourceV3Impl.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildService.kt
Labels: test/passed

#3471 feature: agent支持第二网关配置 #3463
  src/agent/src/pkg/api/type.go
  src/agent/src/pkg/config/config.go
  src/agent/src/pkg/heartbeat/heartbeat.go
  src/backend/ci/core/common/common-environment-thirdpartyagent/src/main/kotlin/com/tencent/devops/common/environment/agent/AgentGrayUtils.kt
  src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/pojo/thirdPartyAgent/HeartbeatResponse.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/thirdPartyAgent/ThirdPartyAgentDao.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/init/EnvironmentConfig.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/AgentUrlService.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/BluekingAgentUrlServiceImpl.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/slave/SlaveGatewayService.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/DownloadAgentInstallService.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdPartyAgent/ThirdPartyAgentMgrService.kt
  support-files/agent-package/config/.agent.properties
  support-files/sql/1001_ci_environment_ddl_mysql.sql
  support-files/sql/2004_ci_environment-update_v1.2_mysql.sql
Labels: area/ci/backend, test/passed

#3451 feat: 保留buildTask，buildVariables，workspace等参数，供pipelineScript插件读取 #3119
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Constants.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
Labels: area/ci/agent, test/passed
