Repository TencentBlueKing/bk-ci, pull requests merged in 2024-07, with the labels that each got.

#10616 feat：流水线版本管理机制 #8161 解决发布的并发问题
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/lock/PipelineReleaseLock.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/actions/internal/PipelineYamlManualAction.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/git/service/PacGitApiService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/git/service/TGitApiService.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsOpProjectServiceImpl.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceScmOauthResource.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmOauthResourceImpl.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmOauthService.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmOauthService.kt
Labels: for test

#10597 feat：Git事件触发器自定义触发条件支持通过 Code 方式定义 #10497
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/on/MrRule.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/on/PushRule.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/resources/schema/V3_0/ci.json
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
Labels: for test

#10596 feat：P4触发器支持 Code 编写 #10551
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/on/PreTriggerOnV3.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/on/TriggerOn.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/utils/ScriptYmlUtils.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/resources/schema/V3_0/ci.json
Labels: for test

#10539 feat：子流水线调用插件参数传递方式优化 #9943
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserSubPipelineInfoResource.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserSubPipelineInfoResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceSubPipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
Labels: for test

#10538 feat: SVN事件触发的路径匹配规则增加兜底逻辑 #10510
  src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/svn/SvnCommitEvent.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/svn/SvnCommitTriggerHandler.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/svn/service/TriggerSvnService.kt
Labels: for test

#10435 feat：支持在父流水线中查看异步执行的子流水线的状态 #10260
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/auth/Header.kt
  src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/dispatcher/pipeline/mq/MQ.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/Element.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceSubPipelineResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/record/BuildRecordTask.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordTaskDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStatusService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/record/PipelineRecordModelService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/task/SubPipelineCallAtom.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/init/BuildEngineExtendConfiguration.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/listener/run/start/SubPipelineBuildQueueListener.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceSubPipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
  support-files/sql/1001_ci_archive_process_ddl_mysql.sql
  support-files/sql/1001_ci_process_ddl_mysql.sql
  support-files/sql/2004_v3.x/2030_ci_archive_process-update_v3.0_mysql.sql
  support-files/sql/2004_v3.x/2030_ci_process-update_v3.0_mysql.sql
Labels: for test

#10620 feat: pipeline as code issue #8125
  src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
  src/frontend/devops-pipeline/src/components/ExecDetail/Summary.vue
  src/frontend/devops-pipeline/src/utils/monacoEditor.js
  src/frontend/devops-pipeline/src/views/subpages/YamlPipelineEditor.vue
Labels: for test

#10628 feat：支持在父流水线中查看异步执行的子流水线的状态 #10260
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResource.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
Labels: for test

#10613 feat: 流水线中有多个CodeCC插件时，质量红线跳转链接要能跳转到相应任务 #10605
  src/backend/ci/core/common/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccUtils.kt
  src/backend/ci/core/common/common-quality/src/main/kotlin/com/tencent/devops/common/quality/pojo/QualityRuleInterceptRecord.kt
  src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleCheckService.kt
Labels: for test, tested, area/qualitygate/backend

#10603 feat：制品下载无反应问题 #10555
  src/frontend/devops-pipeline/src/components/ArtifactDownloadButton.vue
Labels: for test

#10635 bug: 禁用项目不应该统计用户数 #10634
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/CacheProjectInfoService.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/ProjectBuildSummaryServiceImpl.kt
Labels: for test

#10650 bug：项目最大可授权范围 序列化对比问题 #10649
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
Labels: for test, tested

#10644 perf：支持java插件target引用变量来设置jar包执行路径 #10643
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/constant/StoreMessageCode.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/AtomBusHandleService.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/CommonAtomBusHandleHandleServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/GolangAtomBusHandleHandleServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/JavaAtomBusHandleHandleServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/MarketAtomCommonServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/NodeJsAtomBusHandleHandleServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/PythonAtomBusHandleHandleServiceImpl.kt
  support-files/i18n/store/message_en_US.properties
  support-files/i18n/store/message_zh_CN.properties
Labels: for test, tested

#10624 修复更新组件关联初始化项目信息时未删除关联的调试项目信息 #10621
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/StoreProjectRelDao.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreProjectServiceImpl.kt
Labels: for test, tested

#10652 bug:研发商店通用接口国际化配置调整 #10640
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/OpStoreComponentResource.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/ServiceStoreComponentResource.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/UserStoreComponentQueryResource.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/MyStoreComponent.kt
Labels: for test

#10659 feat: 修复iam初始化脚本 #10658
  helm-charts/core/ci/templates/init/init.iam-rbac.yaml
  helm-charts/core/ci/templates/init/init.iam.yaml
Labels: for test

#10674 归档构件的制品页,显示有误,路径不完整,缺少文件大小 #10667
  src/frontend/devops-pipeline/src/components/ExecDetail/Artifactory.vue
Labels: for test

#10420 bug: 回收站搜索不可用 #8440
  src/frontend/devops-pipeline/src/views/PipelineList/PipelineManageList.vue
Labels: for test

#10677 bugfix: 重试重新调度导致复用无法解锁 #10675
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/AgentReuseMutexCmd.kt
Labels: for test

#10653 feat：依赖的服务未部署时的交互优化 #10612
  helm-charts/core/ci/templates/init/init.iam.yaml
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/service/ServiceVO.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsUserProjectServiceServiceImpl.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/UserRepositoryConfigResource.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/RepositoryConfig.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/enums/RepositoryConfigStatusEnum.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/UserRepositoryConfigResourceImpl.kt
  support-files/bkiam/0003_bk_ci_20200623-2120_iam.json
  support-files/bkiam/0003_resouce_20211221_iam-v1.7.json
  support-files/bkiam/0004_bk_ci_20200623-2120_iam.json
  support-files/bkiam/0004_instance-views_20211125_iam-v1.7.json
  support-files/bkiam/0005_action_20200623-2120_iam.json
  support-files/bkiam/0005_action_20211125_iam-v1.7.json
  support-files/bkiam/0006_bk_ci_20200623-2120_iam.json
  support-files/bkiam/0006_group_20211125_iam-v1.7.json
  support-files/bkiam/0007_bk_ci_20200804-1047_iam.json
  support-files/bkiam/0007_create-related_20211125_iam-v1.7.json
  support-files/bkiam/bkiam_do_migrate.py
  support-files/sql/1001_ci_project_ddl_mysql.sql
  support-files/sql/2004_v3.x/2030_ci_project-update_v3.0_mysql.sql
  support-files/sql/5001_init_dml/5001_ci_project-init_dml_mysql.sql
Labels: for test

#10664 feat：定时触发器支持指定代码库和分支 #10300
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/enums/TriggerRepositoryType.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ElementTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/on/SchedulesRule.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/resources/schema/V3_0/ci.json
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
Labels: for test

#10673 bug: 忽略工蜂webhook测试请求 #10666
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitIssueTriggerHandler.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/external/ExternalScmResource.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/external/ExternalScmResourceImpl.kt
Labels: for test

#10685 bug: 合作版工蜂force push触发流水线失败 #10680
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/GitScmService.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceTGitResource.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceTGitResourceImpl.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/tgit/ITGitService.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/tgit/TGitService.kt
Labels: for test

#10669 feat: pac ui编辑流水线 issue #8125
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/NotifyTab.vue
  src/frontend/devops-pipeline/src/components/pipelineSetting/NotifySetting.vue
  src/frontend/locale/pipeline/en-US.json
  src/frontend/locale/pipeline/zh-CN.json
Labels: for test

#10684 bug：保存流水线模板权限问题 #10681
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingFacadeService.kt
Labels: for test

#10698 feat：流水线版本管理机制 #8161 企业微信组通知类型兼容
  src/backend/ci/core/common/common-pipeline-yaml/src/main/resources/schema/V3_0/ci.json
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/setting/Subscription.kt
  src/backend/ci/core/notify/biz-notify/src/main/kotlin/com/tencent/devops/notify/service/notifier/WeworkGroupNotifier.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingVersionDao.kt
Labels: for test

#10699 bug: 归档报告插件创建token没有实现 #10693
  src/backend/ci/core/worker/worker-agent/src/main/kotlin/com/tencent/devops/agent/service/SampleRepoServiceImpl.kt
  src/backend/ci/core/worker/worker-agent/src/main/resources/.agent.properties
  src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/archive/ArchiveResourceApi.kt
  src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/archive/BkRepoArchiveResourceApi.kt
  src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/report/BkRepoReportResourceApi.kt
  src/backend/ci/core/worker/worker-api-sdk/src/main/kotlin/com/tencent/devops/worker/common/api/report/ReportResourceApi.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/BuildArchiveGetTask.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/CustomizeArchiveGetTask.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/ReportArchiveTask.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/plugin/worker/task/archive/SingleFileArchiveTask.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/archive/ArchiveSDKApi.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/api/report/ReportSDKApi.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/logger/LoggerService.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/RepoService.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/service/RepoServiceFactory.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/script/ScriptTask.kt
Labels: for test

#10708 bug: stream 流水线MR触发时分支变量值有误 #10707
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
Labels: for test

#10702 bug:开源版插件升级版本未刷新LATEST_TEST_FLAG标识状态 #10701
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/SampleAtomReleaseServiceImpl.kt
Labels: for test

#10623 bug:有时候取消final stage后，构建未彻底结束 #10619
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildStageDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineStageService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/StageControl.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/CheckPauseReviewStageCmd.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/stage/impl/UpdateStateForStageCmdFinally.kt
Labels: for test

#10690 优化审计相关逻辑 #10671
  src/backend/ci/core/common/common-audit/src/main/kotlin/com/tencent/devops/common/audit/ActionAuditContent.kt
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/ActionId.kt
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/ResourceTypeId.kt
Labels: for test

#10722 修复社区版3.0 的bug
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ElementTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/pojo/WebHookTriggerElementChanger.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/TemplateInstanceCreateRequest.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitlabWebHookTriggerElement.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/param/GitWebhookElementParams.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/param/GitlabWebhookElementParams.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/util/WebhookUtils.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineVersionResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineVersionResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/notify/command/impl/BluekingNotifySendCmd.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
  support-files/i18n/message_en_US.properties
  support-files/i18n/message_zh_CN.properties
  support-files/sql/5001_init_dml/5001_ci_store-init_dml_mysql.sql
Labels: for test

#10687 bug:无编译环境构建机执行带审核插件的矩阵job问题 #10599
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/detail/BaseBuildDetailService.kt
Labels: for test

#10710 fix: bk-ci-v3.3.0 测试问题修复 #10678
  src/frontend/devops-codelib/src/components/CodeLibDetail/trigger.vue
  src/frontend/devops-nav/src/views/App.vue
  src/frontend/devops-nav/src/views/Home.vue
  src/frontend/devops-pipeline/src/components/AtomSelector/index.vue
Labels: for test
