Repository TencentBlueKing/bk-ci, pull requests merged in 2024-08, with the labels that each got.

#10754 [stream] 优化触发流程，减少触发时长 #10753
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/creator/ModelCreate.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/creator/ModelElement.kt
Labels: for test

#10731 feat：流水线版本管理机制 #8161 优化code模式转换
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ContainerTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ElementTransfer.kt
Labels: for test

#10729 feat: 优化流水线导出结构顺序 #10728
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/JsonUtil.kt
  src/backend/ci/core/common/common-pipeline/src/test/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementTest.kt
  src/backend/ci/core/common/common-pipeline/src/test/resources/windowsElement.json
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
Labels: for test

#10723 【蓝盾-产品-已评审】流水线支持展示运行进度 #7932 fix
  src/backend/ci/core/worker/worker-agent/src/test/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtilsTest.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/utils/CommandLineUtils.kt
Labels: for test

#10712 [stream]新增获取组成员 #10711
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/CentralizedStramPermissionServiceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/GithubStreamPermissionServiceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/GitlabStreamPermissionServiceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/StreamPermissionProjectServiceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/StreamPermissionServiceImpl.kt
Labels: for test

#10762 构建环境Agent并发上限为0不生效 #10740
  src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/ThirdPartyDispatchService.kt
Labels: for test

#10773 bug: 归档构件的制品页,显示有误,路径不完整,缺少文件大小 #10667
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/BkRepoArchiveFileServiceImpl.kt
Labels: for test

#10775 Revert "bugfix: 触发时前端手动跳过的矩阵依然运行 #10751"
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Container.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/NormalContainer.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/TriggerContainer.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/VMBuildContainer.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/CheckConditionalSkipContainerCmd.kt
Labels: for test

#10772 bugfix: 修复矩阵code校验时存在的并发问题 #10771
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/MatrixContextUtils.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/enums/VariableType.kt
  src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/util/MatrixYamlCheckUtilsTest.kt
Labels: for test

#10744 feat：构建历史列表支持展示构建信息字段 #10724
  src/frontend/devops-pipeline/src/utils/pipelineConst.js
  src/frontend/locale/pipeline/en-US.json
  src/frontend/locale/pipeline/zh-CN.json
Labels: for test

#10757 修复3.0模板一些bug
  src/backend/ci/core/common/common-db-base/src/main/kotlin/com/tencent/devops/common/db/utils/JooqUtils.kt
  src/backend/ci/core/common/common-db-base/src/test/kotlin/com/tencent/devops/common/db/utils/JooqUtilsTest.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/TriggerContainer.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/param/GitlabWebhookElementParams.kt
  src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwBuildResourceV4.kt
  src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwBuildResourceV4Impl.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserBuildResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/enums/HistorySearchType.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/PipelineDetail.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/utils/PipelineUtils.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserBuildResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/webhook/WebhookRequestService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlFacadeService.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/UserRepositoryConfigResourceImpl.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/UserRepositoryPacResourceImpl.kt
  support-files/i18n/message_en_US.properties
  support-files/i18n/message_zh_CN.properties
  support-files/sql/5001_init_dml/5001_ci_process-init_ddl_mysql.sql
  support-files/templates/#etc#ci#application-repository.yml
Labels: for test

#10779 bugfix: agent没有区域信息时默认没有bkrepo的网关 #10778
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/slave/SlaveGatewayService.kt
Labels: for test

#10739 fix: bk-ci-v3.3.0 测试问题修复 #10678
  src/frontend/devops-atomstore/src/assets/scss/devops-common.scss
  src/frontend/devops-nav/src/router/index.ts
  src/frontend/devops-nav/src/store/modules/platform-config.js
  src/frontend/devops-nav/src/utils/iframeUtil.ts
  src/frontend/devops-permission/src/views/applyPermission/apply-permission.vue
  src/frontend/devops-permission/src/views/applyPermission/scroll-load-list.vue
  src/frontend/devops-permission/src/views/applyPermission/search-select.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/PipelineBreadCrumb.vue
  src/frontend/devops-pipeline/src/views/PipelineList/PipelineManageList.vue
  src/frontend/devops-pipeline/src/views/subpages/ExecDetail.vue
  src/frontend/devops-pipeline/src/views/template/index.vue
  src/frontend/locale/nav/en-US.json
  src/frontend/locale/nav/zh-CN.json
  src/frontend/locale/permission/en-US.json
  src/frontend/locale/permission/zh-CN.json
Labels: for test

#10768 feat: 蓝盾网关信任安全域名的cors-header #10767
  src/gateway/core/lua/cors_filter.lua
Labels: for test, tested

#10614 feat: github pr检查输出质量红线报告 #10607
  src/backend/ci/core/common/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccUtils.kt
  src/backend/ci/core/misc/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/ScmCheckService.kt
  src/backend/ci/core/misc/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/git/CodeWebhookService.kt
  src/backend/ci/core/misc/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/utils/QualityUtils.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/scm/ScmProxyService.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/github/GithubCheckRuns.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/sdk/github/pojo/CheckRunOutput.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/github/GithubService.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/utils/scm/QualityUtils.kt
Labels: for test

#10783 feat: 全局配置title/footer/logo/favicon/产品名称 #10678
  src/frontend/bk-pipeline/package.json
  src/frontend/devops-nav/src/router/index.ts
  src/frontend/devops-nav/src/store/modules/platform-config.js
  src/frontend/devops-nav/src/utils/iframeUtil.ts
  src/frontend/devops-nav/src/views/App.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/PipelineBreadCrumb.vue
  src/frontend/devops-pipeline/src/views/PipelineList/PipelineManageList.vue
  src/frontend/devops-pipeline/src/views/subpages/ExecDetail.vue
  src/frontend/devops-pipeline/src/views/template/index.vue
  src/frontend/devops-quality/src/views/create_rules.vue
  src/frontend/locale/quality/en-US.json
  src/frontend/locale/quality/zh-CN.json
Labels: for test

#10797 bugfix: Agent复用同级节点时跳过了复用锁 #10795
  src/backend/ci/core/common/common-pipeline-yaml/src/main/resources/schema/V3_0/ci.json
  src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/ThirdPartyDispatchService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/AgentReuseMutexCmd.kt
Labels: for test

#10812 feat:优化dockerhost dockerRun容器日志获取接口 #10811
  src/backend/ci/core/dockerhost/biz-dockerhost/src/main/kotlin/com/tencent/devops/dockerhost/services/container/ContainerCustomizedRunHandler.kt
Labels: for test

#10805 feat: 全局配置title/footer/logo/favicon/产品名称 #10678
  src/frontend/devops-nav/src/router/index.ts
  src/frontend/devops-nav/src/utils/iframeUtil.ts
Labels: for test

#10828 bugfix: 构建历史接口的调试记录查询问题 #10814
  src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/process/ProcessDao.kt
Labels: for test

#10829 feat：支持管理员查看项目成员 #9620
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceMemberService.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/utils/NodeStringIdUtils.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/AuthPipelineService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
Labels: for test

#10830 feat：支持管理员查看项目成员 #9620
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/github/GithubTokenService.kt
Labels: for test

#10835 feat：支持管理员查看项目成员 #9620
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/migrate/OpAuthMigrateResource.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupDao.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/config/RbacAuthConfiguration.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/AuthResourceService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/PermissionSubsetManagerService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupSyncService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/migrate/AbMigratePolicyService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/migrate/MigrateResourceGroupService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/migrate/RbacPermissionMigrateService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionMigrateService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/OpAuthMigrateResourceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionMigrateService.kt
Labels: for test

#10541 feat：流水线权限代持功能重构 #10356
  src/frontend/devops-pipeline/src/components/PipelineDetailTabs/DelegationPermission.vue
  src/frontend/devops-pipeline/src/components/PipelineDetailTabs/index.js
  src/frontend/devops-pipeline/src/store/modules/pipelines/pipelines.js
  src/frontend/devops-pipeline/src/utils/permission.js
  src/frontend/devops-pipeline/src/views/subpages/History.vue
  src/frontend/locale/pipeline/en-US.json
  src/frontend/locale/pipeline/zh-CN.json
  src/frontend/svg-sprites/pipeline/help-document-fill.svg
Labels: for test

#10837 feat：流水线权限代持功能重构 #10356
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
Labels: for test

#10839 feat：支持管理员查看项目成员 #9620 项目成员交接代码库时, 没有获取到组成员
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/RepositoryService.kt
Labels: for test, tested

#10810 feat：流水线执行历史支持根据触发人筛选 #10752
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceBuildResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserBuildResource.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServiceBuildResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserBuildResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
Labels: for test

#10777 pref：流水线执行历史表格优化 #10769
  src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
  src/frontend/devops-pipeline/src/views/PipelineList/PatchManageList.vue
  src/frontend/devops-pipeline/src/views/PipelineList/PipelineManageList.vue
Labels: for test

#10856 feat：支持管理员查看项目成员 #9620
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupSyncService.kt
Labels: for test

#10859 feat：流水线模板设置优化 #10857
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingVersionService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateSettingService.kt
Labels: for test, tested

#10849 bugfix: 触发时前端手动跳过的矩阵依然运行 #10751
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordContainerDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/record/BuildRecordTaskDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/ContainerBuildRecordService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
Labels: for test

#10820 bug: 流水线Job异步开机后随即用户取消流水线，异步开机异常导致流水线状态刷新异常 #10816
  src/backend/ci/core/common/common-dispatch-sdk/src/main/kotlin/com/tencent/devops/common/dispatch.sdk/service/DispatchService.kt
Labels: for test, kind/refactor, area/ci/backend, area/ci/dispatcher, tested

#10791 feat：Code 方式创建的流水线，变量面板-输出变量未获取到问题优化 #10755
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/UserAtomResource.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/resources/UserAtomResourceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/AtomPropService.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/AtomPropServiceImpl.kt
Labels: for test

#10817 feat：Code 方式创建的流水线，变量面板-输出变量未获取到问题优化 #10755
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/atom-output-var.vue
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/param-value-option.vue
  src/frontend/devops-pipeline/src/store/modules/atom/actions.js
  src/frontend/devops-pipeline/src/store/modules/atom/constants.js
  src/frontend/devops-pipeline/src/store/modules/atom/index.js
  src/frontend/devops-pipeline/src/store/modules/atom/mutations.js
Labels: tested

#10853 feat: 项目成员管理 #9620
  src/frontend/devops-atomstore/src/views/edit_atom.vue
  src/frontend/devops-manage/src/components/project-user-selector.vue
  src/frontend/devops-manage/src/components/user-group/components/children/permission-manage/group-aside.vue
  src/frontend/devops-manage/src/components/user-group/components/children/permission-manage/manage-all.vue
  src/frontend/devops-manage/src/components/user-group/components/children/permission-manage/manage-aside.vue
  src/frontend/devops-manage/src/components/user-group/components/children/permission-manage/tab-table.vue
  src/frontend/devops-manage/src/store/userGroupTable.ts
  src/frontend/devops-manage/src/views/manage/permission/permission-manage.vue
Labels: for test

#10867 feat：流水线版本管理机制 #8161 修复模板常量由常量变成变量,流水线常量也应该变成变量
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
Labels: for test

#10854 feat：流水线模板导出后再导入新建失败 issue #10752
  src/frontend/devops-pipeline/src/components/PipelineHeader/DetailHeader.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/PipelineBreadCrumb.vue
  src/frontend/devops-pipeline/src/components/pipelineList/ImportPipelinePopup/index.vue
Labels: for test

#10870 bugfix: 构建历史接口的调试记录查询问题 #10814
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineResourceVersionDao.kt
  support-files/sql/1001_ci_archive_process_ddl_mysql.sql
  support-files/sql/1001_ci_process_ddl_mysql.sql
  support-files/sql/2004_v3.x/2030_ci_archive_process-update_v3.0_mysql.sql
  support-files/sql/2004_v3.x/2030_ci_process-update_v3.0_mysql.sql
Labels: for test

#10831 feat: quality新增matchRuleList的app接口 #10610
  src/backend/ci/core/quality/api-quality/src/main/kotlin/com/tencent/devops/quality/api/v2/AppQualityRuleResource.kt
  src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/resources/v2/AppQualityRuleResourceImpl.kt
Labels: for test

#10881 bug: 修正取消正在运行中构建可能产生的慢逻辑 #10874 修正锁的粒度，并发组与传统旧版的串行队列区分开
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildMonitorControl.kt
Labels: for test

#10879 bugfix: Agent复用在流水线重试的场景下存在问题 #10877
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/pojo/AgentReuseMutexTree.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
  src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/pojo/AgentReuseMutexTest.kt
Labels: for test

#10878 feat：流水线模板设置优化 #10857
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/cron/AuthCronSyncGroupAndMember.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateCommonService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateSettingService.kt
Labels: for test, tested

#10894 bug: 修正取消正在运行中构建可能产生的慢逻辑 #10874 fix
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
Labels: for test

#10842 feat：支持管理员查看项目成员 #9620 子流水线启动日志埋点
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/extend/ModelCheckPlugin.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/IElementBizPluginService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildAtomElementBizPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildLessAtomElementBizPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/SubPipelineCallElementBizPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/plugin/ElementBizPlugin.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildSubPipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/permission/PipelineAuthorizationService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/trigger/element/TimerTriggerElementBizPlugin.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineElementBizPluginService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineRepositoryService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/webhook/WebHookTriggerElementBizPlugin.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
Labels: for test

#10889 feat：支持管理员查看项目成员 #9620 新增变量BK_CI_AUTHORIZER
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVarUtil.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
Labels: for test

#10888 feat：流水线版本管理机制 #8161 增加返回模版描述字段
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/template/OptionalTemplate.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/template/TemplateDao.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
Labels: for test

#10866 perf: 环境管理添加部分错误码 #10788
  src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/constant/EnvironmentMessageCode.kt
  support-files/i18n/environment/message_en_US.properties
  support-files/i18n/environment/message_zh_CN.properties
Labels: for test
