Repository TencentBlueKing/bk-ci, pull requests merged in 2024-10, with the labels that each got.

#10898 feat：流水线并发运行时，支持限制并发个数和排队 #10718
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ModelTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/Concurrency.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/resources/schema/V3_0/ci.json
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/setting/PipelineSetting.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/Constants.kt
  src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/es/impl/ESServiceImpl.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/setting/PipelineSettingVersion.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingVersionDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/InterceptData.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/QueueInterceptor.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeExtService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineSettingService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingVersionService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineSettingResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/template/UserPTemplateResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
  support-files/sql/1001_ci_process_ddl_mysql.sql
  support-files/sql/2004_v3.x/2030_ci_process-update_v3.0_mysql.sql
Labels: for test

#11005 feature: 流水线日志支持AI修复 #10913
  src/frontend/common-lib/docs.ts
  src/frontend/devops-pipeline/package.json
  src/frontend/devops-pipeline/src/components/ExecDetail/log/jobLog.vue
  src/frontend/devops-pipeline/src/components/ExecDetail/log/pluginLog.vue
  src/frontend/devops-pipeline/src/store/modules/atom/actions.js
  src/frontend/locale/pipeline/en-US.json
  src/frontend/locale/pipeline/zh-CN.json
  src/frontend/pnpm-lock.yaml
Labels: for test, area/ci/frontend, tested

#11040 feat：推荐版本号优化 #10958
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/ShowVariable.vue
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/pipeline-version.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/ReleasePipelineSideSlider.vue
  src/frontend/devops-pipeline/src/components/PipelineVersionsForm.vue
  src/frontend/devops-pipeline/src/store/modules/atom/actions.js
  src/frontend/devops-pipeline/src/views/subpages/History.vue
  src/frontend/locale/pipeline/en-US.json
  src/frontend/locale/pipeline/zh-CN.json
  src/frontend/svg-sprites/pipeline/warning-circle-fill.svg
Labels: for test, tested

#11085 feat: 优化AESUtil #11084
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/auth/Header.kt
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/AESUtil.kt
Labels: for test

#11014 feat: 触发器变量补充 #11002
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/EventCacheService.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/GitScmService.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/github/GithubPrTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitIssueTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitReviewTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitTagPushTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/param/GithubWebHookStartParam.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/pojo/EventRepositoryCache.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/util/WebhookUtils.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/WebhookBuildParameterService.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
Labels: for test

#10992 feat: 触发器条件引入${{variables.xxx}}变量触发不了流水线 #10987
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookUpgradeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/RepoPipelineRefService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlRepositoryService.kt
Labels: for test

#10983 feat: 增加获取工蜂和github oauth url的build接口 #10826
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/BuildOauthResource.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/BuildOauthResourceImpl.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/github/GithubOAuthService.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/GitOauthService.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IGitOauthService.kt
Labels: for test

#10914 feat：源材料展示优化 #10733
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildRepositoryMaterialResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/PipelineBuildMaterial.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineBuildMaterialService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/builds/BuildRepositoryMaterialResourceImpl.kt
Labels: for test

#10912 feat：MR 事件触发器支持 WIP #10683 补充触发器配置详情信息,增加自定义触发控制相关文案
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitWebHookTriggerElement.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeTGitWebHookTriggerElement.kt
  src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
  src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/enums/WebhookI18nConstants.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/ThirdFilter.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
  support-files/i18n/repository/message_en_US.properties
  support-files/i18n/repository/message_zh_CN.properties
Labels: for test

#10521 feat: OpenApi提供转发Turbo编译加速上报资源统计数据接口 #10508
  src/backend/ci/core/openapi/api-openapi/build.gradle.kts
  src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwTurboResourceV4.kt
  src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/ApigwTurboResourceV4Impl.kt
Labels: for test

#11076 第三方构建机DockerUi界面支持 #10962
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ContainerTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/DispatchTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/utils/StreamDispatchUtils.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/image/PoolType.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/agent/ThirdPartyAgentDockerInfo.kt
  src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/utils/ThirdPartyAgentUtils.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/parser/DispatchTypeParserImpl.kt
Labels: for test, tested, streams/for test, streams/tested

#11017 feat：第三方构建机支持使用 dcoker 运行构建任务 #9820
  src/frontend/devops-environment/src/components/devops/environment/basic-information.vue
  src/frontend/devops-environment/src/store/actions.js
  src/frontend/devops-pipeline/src/components/AtomFormComponent/InputParameterArray/index.vue
  src/frontend/devops-pipeline/src/components/AtomSelector/imageSelector.vue
  src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
  src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/LinuxOsDockerImage.vue
  src/frontend/devops-pipeline/src/components/atomFormField/EnumInput/index.vue
  src/frontend/devops-pipeline/src/store/modules/atom/getters.js
  src/frontend/locale/environment/en-US.json
  src/frontend/locale/environment/zh-CN.json
  src/frontend/locale/pipeline/en-US.json
  src/frontend/locale/pipeline/zh-CN.json
Labels: for test

#10998 perf:研发商店组件指标数据字段优化 #10219
  support-files/sql/1001_ci_store_ddl_mysql.sql
  support-files/sql/2003_v2.x/2020_ci_store-update_v2.0_mysql.sql
Labels: for test

#11010 feat: 插件管理菜单对应插件列表增加默认公共插件显示 #10472
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/dao/AtomDao.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/AtomServiceImpl.kt
Labels: for test

#11004 feat：Post action 中支持获取父任务ID #10968
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/StoreConstants.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
Labels: for test

#11030 bug:某些构建场景下插入T_PIPELINE_BUILD_RECORD_TASK表的CONTAINER_ID字段值错误 #11029
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
Labels: for test

#11035 feat：支持查看版本日志 #10938
  src/frontend/devops-manage/src/views/manage/permission/permission-manage.vue
  src/frontend/devops-nav/package.json
  src/frontend/devops-nav/src/components/Header/index.vue
  src/frontend/devops-nav/src/components/SystemLog/index.vue
  src/frontend/devops-nav/src/store/actions.ts
  src/frontend/locale/nav/en-US.json
  src/frontend/locale/nav/zh-CN.json
  src/frontend/pnpm-lock.yaml
Labels: for test

#11098 feat：当策略为「锁定构建号」时，执行界面可以修改当前值 #11089
  src/frontend/devops-pipeline/src/components/PipelineHeader/EditHeader.vue
  src/frontend/devops-pipeline/src/components/PipelineVersionsForm.vue
  src/frontend/devops-pipeline/src/store/modules/pipelines/build.js
  src/frontend/devops-pipeline/src/views/subpages/preview.vue
  src/frontend/devops-pipeline/src/views/template/edit.vue
Labels: for test

#11027 feat：同步并分表存储资源组权限数据 #10964
  src/frontend/bk-permission/package.json
  src/frontend/bk-permission/src/components/children/permission-manage/group-aside.vue
  src/frontend/devops-manage/src/components/user-group/components/children/permission-manage/group-aside.vue
  src/frontend/devops-manage/src/http/api.ts
  src/frontend/devops-permission/src/components/itsm-group-detail.vue
  src/frontend/devops-permission/src/views/applyPermission/group-detail.vue
Labels: for test, tested

#11110 feat：同步并分表存储资源组权限数据 #10964
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/OpPermissionFacadeResourceImpl.kt
Labels: for test

#11096 feat：Job 互斥组排队时，队列长度支持最长到 50 #10975
  src/frontend/devops-pipeline/src/store/modules/common/jobOptionConfigMixin.js
  src/frontend/locale/pipeline/en-US.json
  src/frontend/locale/pipeline/zh-CN.json
Labels: for test

#11081 feat：流水线列表，增加标签展示 #11054
  src/frontend/devops-pipeline/src/components/pipelineList/PipelineTableView.vue
Labels: for test

#11072 feat：通过子流水线调用触发的执行，支持重试 #11015
  src/frontend/devops-pipeline/src/components/PipelineHeader/DetailHeader.vue
Labels: for test

#11073 feat：触发事件重放操作权限控制 #11052
  src/frontend/devops-manage/src/views/manage/project/show-project.vue
  src/frontend/devops-pipeline/src/components/PipelineDetailTabs/TriggerEventChildren.vue
Labels: for test

#11114 feat：支持流水线指标监控 #9860 fix
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/config/MetricsUserListenerConfiguration.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsHeartBeatService.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsUserService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
Labels: for test

#11131 feat: 引擎等MQ场景接入SCS框架 #7443
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/common/AuthCoreConfiguration.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/refresh/event/IamCacheRefreshEvent.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/refresh/event/ManagerOrganizationChangeEvent.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/refresh/event/ManagerUserChangeEvent.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/refresh/event/RefreshBroadCastEvent.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/refresh/event/StrategyUpdateEvent.kt
  src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/stream/constants/StreamBinding.kt
Labels: for test

#11120 访问流水线搜索日志，全屏浏览器查询搜索的日志，上方的搜索栏会消失 #11118
  src/frontend/devops-environment/src/components/devops/environment/basic-information.vue
  src/frontend/devops-nav/src/store/getters.ts
  src/frontend/devops-nav/src/views/Home.vue
  src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/BuildParams.vue
  src/frontend/devops-pipeline/src/components/ExecDetail/detailContainer.vue
  src/frontend/devops-pipeline/src/components/ExecDetail/log/pluginLog.vue
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/pipeline-param-form.vue
  src/frontend/devops-pipeline/src/components/StagePropertyPanel/StageControl.vue
  src/frontend/devops-pipeline/src/store/modules/common/jobOptionConfigMixin.js
  src/frontend/devops-pipeline/src/store/modules/common/optionConfigMixin.js
  src/frontend/locale/pipeline/en-US.json
  src/frontend/locale/pipeline/zh-CN.json
Labels: for test

#11123 feat：同步用户组逻辑优化 #11122
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthOauth2ClientDetailsDao.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupApplyDao.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/config/RbacMQConfiguration.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/listener/SyncGroupAndMemberListener.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupSyncService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionResourceGroupSyncService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceGroupSyncService.kt
Labels: for test

#11129 feat：无编译资源优化环境依赖调度 #11126
  src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/dao/PipelineDockerIPInfoDao.kt
  src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/schedule/VmStatusScheduler.kt
  src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/service/DispatchDockerService.kt
  src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/service/DockerHostBuildService.kt
  src/backend/ci/core/dispatch/biz-dispatch-docker/src/main/kotlin/com/tencent/devops/dispatch/docker/utils/DockerHostUtils.kt
Labels: for test
