Repository TencentBlueKing/bk-ci, pull requests merged in 2024-05, with the labels that each got.

#10270 bugfix: Agent 上下线记录存在重复 #10267
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/cron/ThirdPartyAgentCronClean.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/cron/ThirdPartyAgentHeartBeatJob.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/thirdpartyagent/ThirdPartyAgentActionDao.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/thirdpartyagent/ThirdPartyAgentDao.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ThirdPartAgentService.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ThirdPartyAgentMgrService.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/utils/ThirdAgentActionAddLock.kt
  support-files/i18n/notify/template_en_US.yaml
  support-files/i18n/notify/template_zh_CN.yaml
Labels: for test, tested

#10298 feat：流水线版本管理机制 #8161修复小问题
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ContainerTransfer.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildSummaryDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineStageService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingVersionService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
Labels: for test

#10299 Issue 8125
  src/frontend/devops-nav/src/components/Container/index.vue
  src/frontend/devops-nav/src/views/App.vue
  src/frontend/devops-pipeline/src/components/AtomPropertyPanel/FormField.vue
  src/frontend/devops-pipeline/src/components/AtomSelector/index.vue
  src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
  src/frontend/devops-pipeline/src/components/ModeSwitch.vue
  src/frontend/devops-pipeline/src/components/PipelineDetailTabs/BaseConfig.vue
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/pipeline-param-form.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/EditHeader.vue
  src/frontend/locale/pipeline/en-US.json
  src/frontend/locale/pipeline/zh-CN.json
Labels: for test

#10308 feat：流水线版本管理机制 #8161 版本计算逻辑修复
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TransferMapper.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/VariableTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/utils/NotifyTemplateUtils.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/Notices.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/Variable.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/parsers/template/YamlObjects.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/resources/schema/V3_0/ci.json
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineSettingDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineSettingResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/ParamFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
Labels: for test, tested

#10316 feat：流水线版本管理机制 #8161
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/enums/OperationLogType.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/label/PipelineViewGroupDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/ServicePipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineSettingResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/view/PipelineViewGroupService.kt
  src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/service/view/PipelineViewGroupServiceTest.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
Labels: for test

#10333 feat: pipeline as code issue #8125
  src/frontend/bk-pipeline/dist/bk-pipeline.min.js
  src/frontend/bk-pipeline/src/index.vue
  src/frontend/devops-pipeline/src/components/BuildHistoryTable/FilterBar.vue
  src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
  src/frontend/devops-pipeline/src/components/Pipeline.vue
  src/frontend/devops-pipeline/src/components/PipelineDetailTabs/BuildHistoryTab.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/HistoryHeader.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/PipelineBreadCrumb.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/PreviewHeader.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/ReleasePipelineSideSlider.vue
  src/frontend/devops-pipeline/src/store/modules/atom/getters.js
  src/frontend/devops-pipeline/src/store/modules/pipelines/build.js
  src/frontend/devops-pipeline/src/utils/util.js
  src/frontend/devops-pipeline/src/views/subpages/History.vue
Labels: for test

#10327 perf: 插件执行错误码优化 #10326
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/exception/TaskExecuteException.kt
  src/backend/ci/core/worker/worker-agent/src/test/kotlin/com/tencent/devops/worker/common/exception/TaskExecuteExceptionDecoratorTest.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/exception/TaskExecuteExceptionDecorator.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/EmptyTask.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/market/MarketAtomTask.kt
Labels: tested

#10324 feat: 压缩http返回json串 #10323
  src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/WebAutoConfiguration.kt
Labels: for test

#10335 feat: 网关默认tag不写死 #10334
  src/gateway/core/lua/util/tag_util.lua
Labels: for test, tested

#10296 feat: 网关在auth_request时可以处理302的异常跳转 #10295
  src/gateway/core/error/error.json.handler.conf
  src/gateway/core/lua/util/cookie_util.lua
Labels: for test, tested

#10352 feat：保存流水线时校验引用到的子流水线权限 #10259
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/exception/RemoteServiceException.kt
  src/backend/ci/core/common/common-client/src/main/kotlin/com/tencent/devops/common/client/ClientErrorDecoder.kt
  src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/handler/RemoteServiceExceptionMapper.kt
Labels: for test

#10350 pref：研发商店通用化接口封装 #10123
  src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/api/user/UserBkRepoStaticResource.kt
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/resources/UserBkRepoStaticResourceImpl.kt
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveStorePkgServiceImpl.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/UserDao.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/ServiceStoreResource.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/StoreProjectRelDao.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/resources/ServiceStoreResourceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreComponentManageService.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreProjectService.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreArchiveServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreComponentManageServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreComponentQueryServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreProjectServiceImpl.kt
Labels: for test

#10359 bug: [社区]Bean初始化顺序导致插件上架失败[v2.1.0+] #10357
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/DetailWebsocketPush.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/RecordWebsocketPush.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/StatusWebsocketPush.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreWebsocketPush.kt
Labels: for test, tested, sample/passed

#10353 Pac GitHub
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TransferCacheService.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/inner/TransferCreatorImpl.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/Element.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/agent/LinuxScriptElement.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/agent/ManualReviewUserTaskElement.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/agent/WindowsScriptElement.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/market/MarketBuildAtomElement.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/market/MarketBuildLessAtomElement.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/setting/PipelineSetting.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/TransferUtil.kt
  src/backend/ci/core/process/api-process/src/test/kotlin/com/tencent/devops/process/utils/PipelineYamlVersionUtilsTest.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingVersionService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineSettingFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateSettingService.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/atom/ServiceMarketAtomResource.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/resources/ServiceMarketAtomResourceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/MarketAtomService.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/MarketAtomServiceImpl.kt
Labels: for test

#10361 pref：研发商店通用化接口封装 #10123
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/ServiceStoreComponentResource.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/common/UserStoreComponentQueryResource.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/InstallStoreReq.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/StoreInfoQuery.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/UnInstallReq.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/AtomServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/StoreProjectRelDao.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/resources/ServiceStoreComponentResourceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/resources/UserStoreComponentQueryResourceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreProjectService.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreBaseInstallServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreComponentManageServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreComponentQueryServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreLogServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreProjectServiceImpl.kt
  support-files/sql/1001_ci_store_ddl_mysql.sql
  support-files/sql/2003_v2.x/2020_ci_store-update_v2.0_mysql.sql
Labels: for test

#10376 pref:研发商店logo上传暂不支持svg图片，防止xss攻击 #10374
  support-files/i18n/store/message_en_US.properties
  support-files/i18n/store/message_zh_CN.properties
  support-files/templates/#etc#ci#application-store.yml
Labels: for test

#10360 bug: [社区]Bean初始化顺序导致插件上架失败[v2.1.0+] #10357
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/DetailWebsocketPush.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/RecordWebsocketPush.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/websocket/push/StatusWebsocketPush.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreWebsocketPush.kt
Labels: for test, tested, sample/passed

#10378 feat：openapi 触发流水线运行时，支持传入触发材料 #10302
  src/frontend/devops-pipeline/src/components/ExecDetail/MaterialItem.vue
  src/frontend/devops-pipeline/src/utils/util.js
  src/frontend/svg-sprites/pipeline/icon-link.svg
  src/frontend/svg-sprites/pipeline/link.svg
  src/frontend/svg-sprites/pipeline/openApi.svg
Labels: for test

#10379 feat：openapi 触发流水线运行时，支持传入触发材料 #10302
  src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/ApigwBuildResourceV3.kt
  src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/ApigwBuildResourceV4.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/app/StartBuildContext.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/code/WebhookInfo.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
Labels: for test, tested

#10367 bug: 子流水线插件执行超时，但是没有把子流水线停掉 #10331
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildTaskService.kt
Labels: for test, tested

#10347 feat：代码库触发事件结果展示优化 #10307
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineTriggerEventResource.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/trigger/PipelineTriggerReasonStatistics.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineTriggerEventResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/PipelineTriggerEventDao.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/PipelineTriggerEventAspect.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/PipelineTriggerEventService.kt
Labels: for test, tested

#10345 feat: 新增项目级事件回调 #10146
  src/backend/ci/core/common/common-event/src/main/kotlin/com/tencent/devops/common/event/dispatcher/pipeline/mq/MQ.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/ProjectPipelineCallBack.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/secret/HeaderSecretParam.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/secret/ISecretParam.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineCallbackResource.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/op/OpPipelineCallbackResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/callback/config/ProjectCallbackMQConfiguration.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/callback/listener/ProjectCallbackEventListener.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/dao/ProjectPipelineCallbackDao.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/ProjectPipelineCallBackService.kt
  support-files/sql/1001_ci_process_ddl_mysql.sql
  support-files/sql/2003_v2.x/2020_ci_process-update_v2.0_mysql.sql
Labels: for test, tested

#10288 feat：工蜂MR触发器支持设置监听的action #8949
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeGitWebHookTriggerElement.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/trigger/CodeTGitWebHookTriggerElement.kt
  src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/enums/WebhookI18nConstants.kt
  src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/enums/code/tgit/TGitPushKind.kt
  src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/git/GitMergeRequestEvent.kt
  src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/git/GitTagPushEvent.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/BasePathFilter.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/EventTypeFilter.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/GitHookTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitTagPushTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/param/GitWebhookElementParams.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/param/TGitWebhookElementParams.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/util/WebhookUtils.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/filter/EventTypeFilterTest.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/matcher/GitWebHookMatcherTest.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
  support-files/sql/5001_init_dml/5001_ci_store-init_dml_mysql.sql
Labels: for test

#10294 feat：获取job执行最大并发/项目活跃用户度量数据 #10232
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/migrate/OpAuthMigrateResource.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionApplyService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/migrate/RbacPermissionMigrateService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionMigrateService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/OpAuthMigrateResourceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionMigrateService.kt
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/pojo/ProjectConditionDTO.kt
  src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/api/ServiceMetricsResource.kt
  src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/vo/AtomFailInfoReqVO.kt
  src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/vo/AtomStatisticsInfoReqVO.kt
  src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/vo/BaseQueryReqVO.kt
  src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/vo/MaxJobConcurrencyVO.kt
  src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/vo/PipelineFailInfoQueryReqVO.kt
  src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/vo/ProjectUserCountV0.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/dao/DispatchJobMetricsDao.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/dao/ProjectBuildSummaryDao.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/resources/ServiceMetricsResourceImpl.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/DispatchJobMetricsService.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/ProjectBuildSummaryService.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/DispatchJobMetricsServiceImpl.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/impl/ProjectBuildSummaryServiceImpl.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryVersionService.kt
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/op/OPProjectResource.kt
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/service/ServiceProjectResource.kt
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/api/user/UserProjectResource.kt
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectByConditionDTO.kt
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectProperties.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/OPProjectResourceImpl.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectResourceImpl.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/UserProjectResourceImpl.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/ProjectService.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/util/ProjectUtils.kt
Labels: for test, tested

#10393 pref：研发商店通用化接口封装 #10123
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/resources/UserArchiveComponentPkgResourceImpl.kt
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/ArchiveStorePkgService.kt
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveStorePkgServiceImpl.kt
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveStorePkgToBkRepoServiceImpl.kt
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/store/service/impl/ArchiveStorePkgToLocalServiceImpl.kt
  src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/config/BkRepoClientConfig.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/constant/StoreMessageCode.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreReleaseServiceImpl.kt
  support-files/i18n/store/message_en_US.properties
  support-files/i18n/store/message_zh_CN.properties
Labels: for test

#10113 perf: 研发商店插件运行支持通过task.json中的execution.target字段指定运行参数 #10072
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/AtomEnvRequest.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/AtomBusHandleService.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/CommonAtomBusHandleHandleServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/GolangAtomBusHandleHandleServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/JavaAtomBusHandleHandleServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/MarketAtomEnvServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/NodeJsAtomBusHandleHandleServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/PythonAtomBusHandleHandleServiceImpl.kt
Labels: for test

#10398 feat:变量名为PipelineId时变量不生效 issue #8125
  src/frontend/devops-pipeline/src/components/PipelineDetailTabs/RollbackEntry.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/HistoryHeader.vue
  src/frontend/devops-pipeline/src/components/PipelineHeader/MoreActions.vue
  src/frontend/devops-pipeline/src/components/pipelineSetting/BaseInfo.vue
  src/frontend/devops-pipeline/src/router/router.js
  src/frontend/devops-pipeline/src/store/modules/pipelines/execute.js
  src/frontend/devops-pipeline/src/views/subpages/preview.vue
Labels: for test

#10369 feat: 网关默认tag不写死 #10334
  src/backend/ci/core/common/common-service/src/main/kotlin/com/tencent/devops/common/service/config/CommonConfig.kt
  src/gateway/core/lua/util/tag_util.lua
  support-files/templates/#etc#ci#common.yml
Labels: for test, tested

#10380 feat：流水线版本管理机制 #8161 env功能字段迁移
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/creator/ModelCommon.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/creator/ModelContainer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/creator/ModelElement.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ContainerTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ElementTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/utils/ModelCreateUtil.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/models/job/Job.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v2/utils/StreamDispatchUtils.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/job/Job.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/v3/models/job/PreJob.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/Model.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/VMBuildContainer.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/Element.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementAdditionalOptions.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildTask.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/BuildVariables.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVersionUtils.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/command/container/impl/InitializeMatrixGroupStageCmd.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/task/ITask.kt
Labels: for test

#10407 feat：保存流水线时校验引用到的子流水线权限 #10259
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/extend/ModelCheckPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/IElementBizPluginService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildAtomElementBizPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/MarketBuildLessAtomElementBizPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/atom/plugin/SubPipelineCallElementBizPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/plugin/ElementBizPlugin.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/trigger/element/TimerTriggerElementBizPlugin.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineElementBizPluginService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/template/TemplateFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/webhook/WebHookTriggerElementBizPlugin.kt
Labels: for test

#10422 feat：流水线版本管理机制 #8161 兼容问题修复
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/ElementAdditionalOptions.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/compatibility/v2/V2BuildParametersCompatibilityTransformer.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/extend/DefaultModelCheckPlugin.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/BuildVariableService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
Labels: for test

#10396 feat：工蜂MR触发器支持设置监听的action TencentBlueKing#8949 兼容PAC YML转换
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/TriggerTransfer.kt
Labels: for test

#10441 feat：补全内置变量列表 #10436
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/PipelineBuildParamKey.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVarUtil.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/webhook/TriggerBuildParamUtils.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
Labels: for test

#10443 feat：流水线版本管理机制 #8161 流水线回调增加调试标识
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/ModelDetail.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineBuildDetailService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
Labels: for test

#10442 feat：流水线版本管理机制 #8161 默认补充job id
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Container.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/NormalContainer.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/TriggerContainer.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/VMBuildContainer.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/common/VMUtils.kt
  src/backend/ci/core/process/api-process/src/test/kotlin/com/tencent/devops/process/utils/VMUtilsTest.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
Labels: for test

#10425 feat: 回收站支持流水线名词搜索 #10408
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/user/UserPipelineResource.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserPipelineResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineListFacadeService.kt
Labels: for test
