Repository TencentBlueKing/bk-ci, pull requests merged in 2024-01, with the labels that each got.

#9900 stream 子流水线插件支持调用超时续连 #9899
  src/backend/ci/core/stream/api-stream/src/main/kotlin/com/tencent/devops/stream/pojo/TriggerBuildReq.kt
  src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/OpenApiTriggerService.kt
  src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/actions/streamActions/StreamOpenApiAction.kt
  src/backend/ci/core/stream/biz-stream/src/main/kotlin/com/tencent/devops/stream/trigger/parsers/modelCreate/ModelParameters.kt
Labels: for test, tested, streams/tested

#9906 feat: 区分ci和codecc的默认tag #9895
  src/gateway/core/lua/auth/auth_gray.lua
  src/gateway/core/lua/router_srv.lua
  src/gateway/core/lua/util/tag_util.lua
  src/gateway/core/vhosts/devops.static.conf
  support-files/templates/gateway#core#lua#init.lua
Labels: for test

#9893 pref:为创建文件磁盘缓存对象增加重试机制 #9892
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/factory/BkDiskLruFileCacheFactory.kt
Labels: for test

#9920 bugfix: 流水线小地图未执行节点颜色展示异常 #9919
  src/frontend/devops-pipeline/src/components/MiniMap/index.vue
Labels: for test, tested

#9904 feat: 权限鉴权增加本地缓存 #9903
  src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/utils/AuthCacheKeyUtil.kt
  src/backend/ci/core/common/common-auth/common-auth-rbac/src/main/kotlin/com/tencent/devops/common/auth/api/RbacAuthPermissionApi.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/permission/RbacEnvironmentPermissionService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/permission/RbacPipelinePermissionService.kt
  src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/permission/RbacQualityPermissionServiceImpl.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/permission/RbacRepositoryPermissionService.kt
  src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/permission/RbacCertPermissionService.kt
  src/backend/ci/core/ticket/biz-ticket/src/main/kotlin/com/tencent/devops/ticket/service/permission/RbacCredentialPermissionService.kt
Labels: for test

#9856 bug: [源码未更新时不触发]功能影响后续流水线重试 #9855
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/InterceptData.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/interceptor/TimerTriggerScmChangeInterceptor.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
Labels: for test

#9923 feat: dispatch构建消息检查流水线是否运行逻辑排除流水线取消时的场景 #9922
  src/backend/ci/core/common/common-dispatch-sdk/src/main/kotlin/com/tencent/devops/common/dispatch.sdk/service/DispatchService.kt
Labels: for test

#9925 bug: 插件暂停依赖的redis缓存失效时功能异常 #9913
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/ControlUtils.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineTaskService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/TaskBuildRecordService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/utils/PauseRedisUtils.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineContextService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/PipelineTaskPauseService.kt
  src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/engine/control/ControlUtilsTest.kt
Labels: for test

#9965 feat: 将清理任务的参数暴露出来 #9955
  helm-charts/core/ci/base/default_env.yaml
  scripts/bkenv.properties
  support-files/templates/#etc#ci#application-assembly.yml
  support-files/templates/#etc#ci#application-misc.yml
  support-files/templates/#etc#ci#application-process.yml
Labels: for test

#9884 feat: 离线安装蓝盾 #9881
  docs/install/kubernetes.md
  docs/install/script/bk-ci-offline-image.sh
  helm-charts/core/ci/base/values.yaml
Labels: for test

#9966 pref:增加对分区表的表结构进行校验的gradle插件 #9931
  src/backend/ci/buildSrc/src/main/kotlin/utils/DatabaseUtil.kt
Labels: for test

#9970 feat: kubernetes构建机支持专机配置 #8858
  helm-charts/core/ci/base/default_env.yaml
  helm-charts/core/ci/build_chart.py
  scripts/bkenv.properties
  src/backend/ci/core/dispatch/biz-dispatch-kubernetes/src/main/kotlin/com/tencent/devops/dispatch/kubernetes/service/KubernetesContainerService.kt
  support-files/templates/#etc#ci#application-dispatch.yml
  support-files/templates/#etc#ci#common.yml
Labels: for test

#9988 feat：推动项目关联运营产品 - 提醒项目管理员关联运营产品 #9981
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/pojo/MigrateProjectConditionDTO.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
  support-files/sql/1001_ci_project_ddl_mysql.sql
Labels: for test, tested
