Repository TencentBlueKing/bk-ci, pull requests merged in 2024-12, with the labels that each got.

#11273 bug: 权限管理-权限续期数据同步 #11271
  src/frontend/bk-permission/package.json
  src/frontend/bk-permission/src/components/children/permission-manage/group-aside.vue
  src/frontend/devops-manage/src/components/user-group/components/children/permission-manage/group-aside.vue
  src/frontend/devops-pipeline/src/views/subpages/ExecDetail.vue
Labels: for test

#11277 bug: 创建流水线组失败，导致代码库开启PAC一直显示同步中 #11253
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/inner/TransferCreatorImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/view/PipelineViewService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlRepositoryService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlSyncService.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/code/CodeGitRepositoryService.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
Labels: for test

#11278 bug: 流水线另存为模版,模版名字与流水线名字一样，会报"流水线名称已被使用" #11264
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
Labels: for test

#11297 fix: 执行前暂停的插件弹窗问题处理 #11296
  src/frontend/devops-pipeline/src/components/AtomPropertyPanel/AtomContent.vue
Labels: for test

#11298 perf: environment新增错误码 issue #11279
  src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/constant/EnvironmentMessageCode.kt
  support-files/i18n/environment/message_en_US.properties
  support-files/i18n/environment/message_zh_CN.properties
Labels: tested

#11299 feat: copilot 编辑器支持免登录 #11290
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/constant/RepositoryMessageCode.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/enums/TokenAppTypeEnum.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/pojo/oauth/RepositoryScmToken.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/dao/RepositoryScmTokenDao.kt
  support-files/i18n/repository/message_en_US.properties
  support-files/i18n/repository/message_zh_CN.properties
  support-files/sql/1001_ci_repository_ddl_mysql.sql
Labels: for test

#11149 feat：运行时校验权限代持人权限是否已失效 #10478
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/webhook/PipelineBuildPermissionService.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
Labels: for test

#11272 feat：提供项目管理相关openapi接口 #11231
  src/backend/ci/core/artifactory/api-artifactory/src/main/kotlin/com/tencent/devops/artifactory/constant/ArtifactoryMessageCode.kt
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceProjectAuthResource.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/cron/AuthCronSyncGroupAndMember.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthItsmCallbackDao.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupMemberDao.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/config/RbacAuthConfiguration.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionProjectService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupSyncService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceMemberService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SampleAuthPermissionProjectService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionResourceMemberService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/stream/service/StreamPermissionProjectServiceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceProjectAuthResourceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionProjectService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceMemberService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/lock/CronSyncGroupMembersExpiredTimeLock.kt
  src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/BKRepoProjectUpdateRequest.kt
  src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/pojo/ProjectMetadata.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/dao/AtomDao.kt
  support-files/i18n/artifactory/message_en_US.properties
  support-files/i18n/artifactory/message_zh_CN.properties
Labels: for test, tested

#11303 pref：查询项目接口优化 #11276
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceMonitorSpaceResource.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthMonitorSpaceDao.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionAuthMonitorSpaceService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SampleAuthMonitorSpaceService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceMonitorSpaceResourceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthMonitorSpaceService.kt
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/pojo/ProjectConditionDTO.kt
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectByConditionDTO.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/ProjectDao.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/AbsProjectServiceImpl.kt
Labels: for test, tested

#11306 AI大模型融入 #10825
  src/backend/ci/core/misc/api-gpt/src/main/kotlin/com/tencent/devops/gpt/constant/GptMessageCode.kt
  src/backend/ci/core/misc/biz-gpt/src/main/kotlin/com/tencent/devops/gpt/service/LLMService.kt
  src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/service/doc/DocumentService.kt
  support-files/i18n/misc/message_en_US.properties
  support-files/i18n/misc/message_zh_CN.properties
Labels: for test

#11222 [stream] 项目支持关联到运营产品 #9948 优化
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceProjectResourceImpl.kt
Labels: for test

#11302 bug:插件最新版本使用历史版本修复方式发布后，再用普通方式发布的分支会继承上一次的 #11301
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/atom/MarketAtomUpdateRequest.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/AtomReleaseServiceImpl.kt
Labels: for test

#10886 feat：优化dispatch-sdk调度逻辑对其他服务的依赖 #10882
  src/backend/ci/core/common/common-dispatch-sdk/src/main/kotlin/com/tencent/devops/common/dispatch.sdk/service/DispatchService.kt
Labels: for test

#11316 feat: 升级openresty到1.19 #11295
  docker-images/core/ci/dockerfile/gateway.Dockerfile
  docker-images/core/ci/dockerfile/openresty.Dockerfile
Labels: for test

#11324 feat：Git分支/Tag和Svn分支/Tag类型的变量优化 #10774
  src/backend/ci/buildSrc/src/main/kotlin/constants/Versions.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/cascade/CascadeParam.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/cascade/RepoRefCascadeParam.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/CascadePropertyUtils.kt
Labels: for test

#11323 feat: 优化PUSH事件预匹配逻辑 #11317
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
Labels: for test

#11345 feat: 健康检查优化 #11336
  src/backend/ci/core/common/common-db-sharding/src/main/kotlin/com/tencent/devops/common/db/config/BkShardingDataSourceConfiguration.kt
  src/backend/ci/core/common/common-db/src/main/kotlin/com/tencent/devops/common/db/DBAutoConfiguration.kt
  src/backend/ci/core/common/common-service/src/main/resources/common-service.properties
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/actuate/ProcessHealthIndicator.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineFavorDao.kt
Labels: for test

#11337 feat：Git分支/Tag和Svn分支/Tag类型的变量优化 #10774
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/param-group.vue
  src/frontend/devops-pipeline/src/views/subpages/preview.vue
Labels: for test

#11347 bug: GIT触发器单独监听[新增分支]不生效 #11338
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitPushTriggerHandler.kt
Labels: for test

#11335 bug：插件执行失败时的错误码类型归属错误问题优化 #11294
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/pojo/ErrorType.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/HeartbeatControl.kt
  src/backend/ci/core/worker/worker-agent/src/test/kotlin/com/tencent/devops/worker/common/exception/TaskExecuteExceptionDecoratorTest.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/exception/TaskExecuteExceptionDecorator.kt
Labels: for test

#11318 pref：优化流水线项目下已安装插件关联流水线查询 #11307
  src/backend/ci/core/common/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeCCAutoConfiguration.kt
  src/backend/ci/core/common/common-codecc/src/main/kotlin/com/tencent/devops/plugin/codecc/CodeccApi.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineModelTaskDao.kt
Labels: for test
