Repository TencentBlueKing/bk-ci, pull requests merged in 2025-06, with the labels that each got.

#11815 perf: 日志模块数据清理未支持跨集群 #11814
  src/backend/ci/core/log/api-log/src/main/kotlin/com/tencent/devops/log/api/OpLogResource.kt
  src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/cron/DataCleanJob.kt
  src/backend/ci/core/log/biz-log/src/main/kotlin/com/tencent/devops/log/resources/OpLogResourceImpl.kt
Labels: for test

#11777 feat：stage审核/人工审核通知连接增加定位 #11704
  src/frontend/devops-pipeline/src/components/CheckAtomDialog.vue
  src/frontend/devops-pipeline/src/components/ExecPipeline.vue
  src/frontend/devops-pipeline/src/components/StageReviewPanel/index.vue
  src/frontend/devops-pipeline/src/views/subpages/ExecDetail.vue
Labels: for test

#11757 feat：stage审核/人工审核通知连接增加定位 #11704
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/bean/DefaultPipelineUrlBeanImpl.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/bean/PipelineUrlBean.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/pojo/event/PipelineBuildNotifyEvent.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineStageService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/task/ManualReviewTaskAtom.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/notify/PipelineBuildNotifyListener.kt
Labels: for test

#11794 bug：流水线制品下载限制10Gb问题修复 #11793
  src/frontend/devops-pipeline/src/components/ArtifactDownloadButton.vue
Labels: for test

#11847 pref：用户管理接口优化 #11816
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionApplyService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionManageFacadeServiceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/migrate/AbMigratePolicyService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/migrate/MigrateResultService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/AuthDeptServiceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/DefaultDeptServiceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/DeptService.kt
Labels: tested

#11838 feat：流水线参数在执行预览界面的展示支持联动 #11438
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/BuildFormProperty.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/compatibility/v2/V2BuildParametersCompatibilityTransformer.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/ParamFacadeService.kt
Labels: for test, tested

#11808 pref：无权限跳转申请优化 #11769
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceAuthApplyResource.kt
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/api/service/ServiceResourceGroupResource.kt
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/ApplyJoinGroupSimpleInfo.kt
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/AuthGroupConfigAction.kt
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/vo/AuthApplyRedirectInfoVo.kt
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/vo/AuthRedirectGroupInfoVo.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupDao.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/config/RbacAuthConfiguration.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacCommonService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionApplyService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionAuthMonitorSpaceService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceGroupService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionResourceGroupService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceAuthApplyResourceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceResourceGroupResourceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceGroupService.kt
Labels: for test, tested

#11746 feat: GIT事件触发支持输出TAG描述信息和TAPD单号 #11721
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/constant/CommonMessageCode.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/utils/PipelineConstants.kt
  src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/IScm.kt
  src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeGitScmImpl.kt
  src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/CodeTGitScmImpl.kt
  src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/git/api/GitApi.kt
  src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/enums/TapdRefType.kt
  src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/pojo/GitTagInfo.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/EventCacheService.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/GitScmService.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitMrTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/tgit/TGitTagPushTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/pojo/EventRepositoryCache.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/matcher/GitWebHookMatcherTest.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/PipelineBuildParamKey.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/PipelineVarUtil.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserBuildParametersResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/webhook/TriggerBuildParamUtils.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceScmOauthResource.kt
  src/backend/ci/core/repository/api-repository/src/main/kotlin/com/tencent/devops/repository/api/scm/ServiceScmResource.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmOauthResourceImpl.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/resources/scm/ServiceScmResourceImpl.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmOauthService.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/IScmService.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmOauthService.kt
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/scm/ScmService.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
Labels: for test

#11819 bug: 触发时兼容工蜂SVN仓库名 #11799
  src/backend/ci/core/common/common-webhook/api-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/pojo/code/svn/SvnCommitEvent.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/filter/ProjectNameFilter.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/CodeWebhookTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/handler/svn/SvnCommitTriggerHandler.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/matcher/AbstractScmWebhookMatcher.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/main/kotlin/com/tencent/devops/common/webhook/service/code/matcher/ScmWebhookMatcher.kt
  src/backend/ci/core/common/common-webhook/biz-common-webhook/src/test/kotlin/com/tencent/devops/common/webhook/service/code/filter/ProjectNameFilterTest.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineWebhookDao.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineWebhookService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/plugin/svn/service/TriggerSvnService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/WebhookTriggerService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/trigger/scm/WebhookGrayCompareService.kt
Labels: for test

#11854 feat：系统内置上下文展示，缺少/job/step级别的变量 #10845
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/env-item.vue
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/system-var.vue
Labels: for test

#11826 bug: 插件unzip的时候要去掉根目录 #11825
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/OpAtomServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/utils/StoreFileAnalysisUtil.kt
Labels: for test

#11866 bug:研发商店还未发布处于测试中的组件查询无需按可见范围过滤 #11863
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/MarketStoreQueryDao.kt
Labels: for test

#11872 bug: PAC模式下流水线删除后，流水线组还存在需要优化 #11742
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlFileManager.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlViewService.kt
Labels: for test

#11857 feat: 希望mac公共构建机Xcode版本选择框可以填写变量来控制 #11855
  src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerContent.vue
Labels: for test

#11685 bug:镜像市场首页按推荐使用查询失效 #11675
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/api/image/UserMarketImageResource.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/image/dao/MarketImageDao.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/image/resources/UserMarketImageResourceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/image/service/ImageService.kt
Labels: for test

#11882 pref:研发商店组件版本号规范调整 #11780
  src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/constant/BkStyleEnum.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/StoreConstants.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/publication/StoreBaseCreateRequest.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/version/StoreShowVersionItem.kt
  src/backend/ci/core/store/api-store/src/main/kotlin/com/tencent/devops/store/pojo/common/version/VersionModel.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/MarketAtomServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/MarketStoreQueryDao.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/StoreCommonService.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreBaseCreateServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreBaseUpdateServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreCommonServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreComponentQueryServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreReleaseServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/utils/VersionUtils.kt
  support-files/i18n/message_en_US.properties
  support-files/i18n/message_zh_CN.properties
Labels: for test

#11907 feat: 子流水线调用插件在子流水线开启了PAC场景下支持指定分支 #11768
  src/frontend/devops-pipeline/src/components/AtomFormComponent/SubParameter/index.vue
Labels: for test

#11909 pref:研发商店组件版本号规范调整 #11780
  src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/service/ServiceLocaleResource.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/resources/ServiceLocaleResourceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreCommonServiceImpl.kt
Labels: for test

#11911 pref：支持变量分组按字母排序 #11590
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/children/param-group.vue
Labels: for test

#11812 Agent IP变化的更新机制优化 #11774
  src/agent/agent-slim/cmd/slim.go
  src/agent/agent/Makefile
  src/agent/agent/internal/third_party/dep/fs/fs.go
  src/agent/agent/internal/third_party/dep/fs/rename.go
  src/agent/agent/internal/third_party/dep/fs/rename_windows.go
  src/agent/agent/src/cmd/daemon/main.go
  src/agent/agent/src/cmd/translation_generator/translation_generator.go
  src/agent/agent/src/pkg/agent/agent.go
  src/agent/agent/src/pkg/agent/ask.go
  src/agent/agent/src/pkg/api/api.go
  src/agent/agent/src/pkg/api/type.go
  src/agent/agent/src/pkg/collector/collector.go
  src/agent/agent/src/pkg/config/bus.go
  src/agent/agent/src/pkg/config/bus_test.go
  src/agent/agent/src/pkg/config/config.go
  src/agent/agent/src/pkg/config/config_darwin.go
  src/agent/agent/src/pkg/config/config_linux.go
  src/agent/agent/src/pkg/config/config_win.go
  src/agent/agent/src/pkg/exiterror/exiterror.go
  src/agent/agent/src/pkg/imagedebug/console.go
  src/agent/agent/src/pkg/installer/installer.go
  src/agent/agent/src/pkg/job/build.go
  src/agent/agent/src/pkg/job/build_docker.go
  src/agent/agent/src/pkg/job/do_build.go
  src/agent/agent/src/pkg/job/do_build_win.go
  src/agent/agent/src/pkg/job_docker/job_docker.go
  src/agent/agent/src/pkg/job_docker/opts_test.go
  src/agent/agent/src/pkg/upgrade/operation.go
  src/agent/agent/src/pkg/upgrade/upgrade.go
  src/agent/agent/src/pkg/upgrader/upgrader.go
  src/agent/agent/src/pkg/upgrader/upgrader_win.go
  src/agent/agent/src/pkg/util/command/command.go
  src/agent/agent/src/pkg/util/command/user.go
  src/agent/agent/src/pkg/util/fileutil/fileutil.go
  src/agent/agent/src/pkg/util/httputil/devops.go
  src/agent/agent/src/pkg/util/httputil/httputil.go
  src/agent/agent/src/pkg/util/systemutil/systemutil.go
  src/agent/agent/src/pkg/util/wintask/wintask.go
  src/agent/agent/src/third_components/jdk.go
  src/agent/agent/src/third_components/third_components.go
  src/agent/agent/src/third_components/worker.go
  src/agent/agent/src/third_components/worker_test.go
  src/agent/common/logs/log_rotate.go
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/pojo/agent/AgentPropsInfo.kt
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/pojo/agent/NewHeartbeatInfo.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/model/AgentProps.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/EnvService.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ThirdPartyAgentMgrService.kt
  src/backend/ci/core/environment/biz-environment/src/test/kotlin/com/tencent/devops/environment/service/thirdpartyagent/UpgradeServiceTest.kt
Labels: for test
