Repository TencentBlueKing/bk-ci, pull requests merged in 2025-02, with the labels that each got.

#11422 第三方构建机Docker支持JDK17 #11421
  src/agent/agent/src/pkg/job/build_docker.go
Labels: for test, tested, streams/tested

#11447 feat: 删除老的心跳key #11430
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/thirdpartyagent/BuildAgentThirdPartyAgentResourceImpl.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ThirdPartyAgentMgrService.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/utils/ThirdPartyAgentHeartbeatUtils.kt
Labels: for test

#11374 feat：子流水线插件支持输出触发的子流水线 build_num #11373
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/ProjectBuildId.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
Labels: for test

#11367 feat: 流水线级回调与流水线编排解耦 #11283
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/CallBackData.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/event/ProjectPipelineCallBack.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceCallBackResource.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/PipelineCallbackDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/service/ServiceCallBackResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/control/CallBackControl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/ProjectPipelineCallBackService.kt
  src/backend/ci/core/process/biz-process/src/test/kotlin/com/tencent/devops/process/engine/control/CallBackControlTest.kt
  support-files/sql/1001_ci_process_ddl_mysql.sql
  support-files/templates/#etc#ci#common.yml
Labels: for test

#11429 构建资源锁定支持使用只读变量 #11425
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/type/agent/ThirdPartyAgentDispatch.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/app/StartBuildContext.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/pojo/AgentReuseMutexTree.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
  src/backend/ci/core/process/biz-base/src/test/kotlin/com/tencent/devops/process/pojo/AgentReuseMutexTest.kt
  support-files/i18n/process/message_en_US.properties
  support-files/i18n/process/message_zh_CN.properties
Labels: for test

#11433 feat: 构建资源锁定支持使用只读变量 #11425
  src/frontend/devops-pipeline/src/components/ContainerPropertyPanel/ContainerEnvNode.vue
Labels: for test

#11436 第三方构建机升级优化 #11431
  src/backend/ci/core/environment/biz-environment/build.gradle.kts
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/AgentUpgradeJob.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/UpgradeService.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/upgrade/ProjectScope.kt
  src/backend/ci/core/environment/biz-environment/src/test/kotlin/com/tencent/devops/environment/service/thirdpartyagent/UpgradeServiceTest.kt
Labels: for test

#11458 bug: 修复p4变更文件太多时导致repository服务OOM #11457
  src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/code/p4/api/P4Api.kt
Labels: for test

#11427 pref:分表路由规则优化 #11406
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/TableShardingConfig.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/dao/TableShardingConfigDao.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/TableShardingConfigService.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/ShardingRoutingRuleAssignServiceImpl.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/ShardingRoutingRuleFacadeServiceImpl.kt
  src/backend/ci/core/project/biz-project/src/main/kotlin/com/tencent/devops/project/service/impl/TableShardingConfigServiceImpl.kt
  support-files/sql/1001_ci_project_ddl_mysql.sql
  support-files/sql/2004_v3.x/2030_ci_project-update_v3.0_mysql.sql
Labels: for test

#11424 bug:插件关联的流水线数量在流水线并发保存时可能计算出错 #11419
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineAtomStatisticsService.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/atom/service/impl/MarketAtomStatisticServiceImpl.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/dao/StoreStatisticTotalDao.kt
  src/backend/ci/core/store/biz-store/src/main/kotlin/com/tencent/devops/store/common/service/impl/StoreTotalStatisticServiceImpl.kt
Labels: for test

#11370 feat: taskControl的loop循环太久导致Consumer线程池被占满问题 #11352
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/atom/IAtomTask.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/control/VmOperateTaskGenerator.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/vm/DispatchVMStartupTaskAtom.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/TaskControl.kt
  src/backend/ci/core/worker/worker-common/src/main/kotlin/com/tencent/devops/worker/common/Runner.kt
Labels: for test

#11410 feat: api文档更新 #11409
  src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/environment/ApigwEnvironmentAgentResourceV3.kt
  src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v3/environment/ApigwEnvironmentResourceV3.kt
  src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/environment/ApigwEnvironmentAgentResourceV4.kt
  src/backend/ci/core/openapi/api-openapi/src/main/kotlin/com/tencent/devops/openapi/api/apigw/v4/environment/ApigwEnvironmentResourceV4.kt
  src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v3/environment/ApigwEnvironmentResourceV3Impl.kt
  src/backend/ci/core/openapi/biz-openapi/src/main/kotlin/com/tencent/devops/openapi/resources/apigw/v4/environment/ApigwEnvironmentResourceV4Impl.kt
Labels: for test

#11416 数据库文档更新 1.0.7
  docs/overview/db/devops_ci_artifactory.md
  docs/overview/db/devops_ci_auth.md
  docs/overview/db/devops_ci_dispatch.md
  docs/overview/db/devops_ci_environment.md
  docs/overview/db/devops_ci_image.md
  docs/overview/db/devops_ci_log.md
  docs/overview/db/devops_ci_notify.md
  docs/overview/db/devops_ci_op.md
  docs/overview/db/devops_ci_openapi.md
  docs/overview/db/devops_ci_plugin.md
  docs/overview/db/devops_ci_process.md
  docs/overview/db/devops_ci_project.md
  docs/overview/db/devops_ci_quality.md
  docs/overview/db/devops_ci_repository.md
  docs/overview/db/devops_ci_sign.md
  docs/overview/db/devops_ci_store.md
  docs/overview/db/devops_ci_ticket.md
Labels: for test

#11417 feat: 支持流水线构建状态上报 #11413
  src/backend/ci/core/metrics/api-metrics/src/main/kotlin/com/tencent/devops/metrics/pojo/po/MetricsEventPO.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/config/MetricsUserConfig.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsEventService.kt
  src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsUserService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/vmbuild/EngineVMBuildService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildEndControl.kt
  src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
Labels: for test

#11426 feat: Code禁用流水线切换到使用新方式 #11420
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/ModelTransfer.kt
  src/backend/ci/core/common/common-pipeline-yaml/src/main/kotlin/com/tencent/devops/process/yaml/transfer/pojo/ModelTransferInput.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineInfoDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineTransferYamlService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineInfoFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/yaml/PipelineYamlRepositoryService.kt
Labels: for test

#11376 fix: 【Stream】selector组件下拉选项列表通过接口获取，数据为空 #11375
  src/frontend/devops-stream/src/components/ui-form/mixins.js
Labels: for test

#11459 pref：审计相关优化 #11396
  src/backend/ci/core/auth/api-auth/src/main/kotlin/com/tencent/devops/auth/pojo/enum/HandoverAction.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/dao/AuthResourceGroupDao.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionManageFacadeServiceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionProjectService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/rbac/service/RbacPermissionResourceMemberService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/provider/sample/service/SamplePermissionResourceMemberService.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/open/OpenResourceMemberResourceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/resources/service/ServiceResourceMemberResourceImpl.kt
  src/backend/ci/core/auth/biz-auth/src/main/kotlin/com/tencent/devops/auth/service/iam/PermissionResourceMemberService.kt
  src/backend/ci/core/common/common-audit/src/main/kotlin/com/tencent/devops/common/audit/ActionAuditContent.kt
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/ActionId.kt
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/AuthResourceType.kt
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/ResourceTypeId.kt
  src/backend/ci/core/common/common-auth/common-auth-api/src/main/kotlin/com/tencent/devops/common/auth/api/pojo/BkAuthGroup.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/UserBuildResourceImpl.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectCreateUserInfo.kt
  src/backend/ci/core/project/api-project/src/main/kotlin/com/tencent/devops/project/pojo/ProjectDeleteUserInfo.kt
  support-files/bkiam-rbac/0005_action_20221213_iam-rbac.json
Labels: for test

#11460 bug: MR事件触发回写检查异常 #11456
  src/backend/ci/core/misc/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/ScmCheckService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/SubPipelineTaskService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineCheckService.kt
Labels: for test

#11469 feat：支持管理我的 OAUTH #10995
  src/backend/ci/core/repository/biz-repository/src/main/kotlin/com/tencent/devops/repository/service/github/GithubOAuthService.kt
Labels: for test

#11471 bug: 质量红线生效范围选择模板保存后，再点开查看数据没有正确展示 #11470
  src/backend/ci/core/quality/biz-quality/src/main/kotlin/com/tencent/devops/quality/service/v2/QualityRuleService.kt
Labels: for test, tested, area/qualitygate/backend

#11484 bug: 通过api保存的新版本可能覆盖旧版本 #11418 发送事件问题
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineVersionFacadeService.kt
Labels: for test

#11485 feat: environment的redis迁移 #11464
  src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/controller/BuildAgentBuildResourceImpl.kt
Labels: for test

#11476 feat: APP的manualStartupInfo新增url处理 #11475
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/enums/PlatformEnum.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/cascade/BuildCascadeProps.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/api/app/AppPipelineBuildResourceImpl.kt
Labels: for test

#11491 bug: 流水线版本管理与触发的并发问题 #11490
  src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/pojo/pipeline/PipelineResourceVersion.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineResourceVersionDao.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
  src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/pipeline/PipelineBuildService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/webhook/PipelineBuildWebhookService.kt
Labels: for test

#11502 bug：文件通用下载接口的文件路径参数校验加强 #11501
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/resources/BuildFileResourceImpl.kt
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/resources/UserFileResourceImpl.kt
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/resources/UserReportStorageResourceImpl.kt
  src/backend/ci/core/artifactory/biz-artifactory/src/main/kotlin/com/tencent/devops/artifactory/service/impl/DiskArchiveFileServiceImpl.kt
  src/backend/ci/core/common/common-archive/src/main/kotlin/com/tencent/devops/common/archive/util/PathUtil.kt
Labels: for test

#11479 pref:流水线构建重试时增加时间限制 #11478
  src/backend/ci/buildSrc/src/main/kotlin/plugins/task-sharding-db-table-check.gradle.kts
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
Labels: for test

#11492 bug: 当被替换插件参数发生变化时，插件替换工具不一定能兼容 #11486
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/util/ReflectUtil.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/market/MarketBuildAtomElement.kt
  src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/pojo/element/market/MarketBuildLessAtomElement.kt
  src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/dao/process/ProcessDao.kt
  src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/PipelineAtomReplaceCronService.kt
Labels: for test

#11509 feat: 将tag的缓存有效期从5s改为60s #11508
  src/gateway/core/lua/util/loadbalance_util.lua
  src/gateway/core/lua/util/tag_util.lua
Labels: for test, tested

#11474 feat：执行历史界面制品列表UI优化 #11012
  src/frontend/devops-pipeline/src/components/BuildHistoryTable/index.vue
  src/frontend/devops-pipeline/src/components/Outputs/index.vue
  src/frontend/devops-pipeline/src/scss/mixins/ellipsis.scss
Labels: for test

#11441 feat：流水线变量面板，上下滚动时固定顶部操作区域 #11378
  src/frontend/devops-pipeline/src/components/PipelineEditTabs/components/pipeline-param.vue
Labels: for test

#11450 feat：环境-节点管理列表支持按照状态等字段搜索 #11445
  src/backend/ci/core/common/common-api/src/main/kotlin/com/tencent/devops/common/api/constant/CommonConstants.kt
  src/backend/ci/core/dispatch/api-dispatch/src/main/kotlin/com/tencent/devops/dispatch/api/ServiceAgentResource.kt
  src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/controller/ServiceAgentResourceImpl.kt
  src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/dao/ThirdPartyAgentBuildDao.kt
  src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/ThirdPartyAgentService.kt
  src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/UserNodeResource.kt
  src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/api/thirdpartyagent/UserThirdPartyAgentResource.kt
  src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/constant/EnvironmentMessageCode.kt
  src/backend/ci/core/environment/api-environment/src/main/kotlin/com/tencent/devops/environment/pojo/NodeWithPermission.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/NodeDao.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/dao/thirdpartyagent/ThirdPartyAgentDao.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/UserNodeResourceImpl.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/resources/thirdpartyagent/UserThirdPartyAgentResourceImpl.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/NodeService.kt
  src/backend/ci/core/environment/biz-environment/src/main/kotlin/com/tencent/devops/environment/service/thirdpartyagent/ThirdPartyAgentMgrService.kt
  support-files/i18n/environment/message_en_US.properties
  support-files/i18n/environment/message_zh_CN.properties
  support-files/i18n/message_en_US.properties
  support-files/i18n/message_zh_CN.properties
  support-files/sql/1001_ci_environment_ddl_mysql.sql
  support-files/sql/2004_v3.x/2030_ci_environment-update_v3.0_mysql.sql
Labels: for test
